In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
        

diabetes = pd.read_csv('/kaggle/input/pima-indians-diabetes-database/diabetes.csv')

print(diabetes.info())

# let see how many rows the data has
print(len(diabetes))
# there are 768 rows in the data

#let's see the number of missing values in the data 
diabetes.isnull().sum()

#let's look deeper into the data and look at summary statistics
diabetes.describe()

# there are some unusual aspects to the data: the min value for BMI is 0 and insulin as well. Also the 
# maximum value for insulin is 846.0 which is abnormally high. Also the max value for pregnancies is 17 which
# while not impossible, does seem unusually high

# replace the instances of 0 with NaN 
diabetes[['Glucose','BloodPressure','SkinThickness','Insulin','BMI']] = diabetes[['Glucose','BloodPressure','SkinThickness','Insulin','BMI']].replace(0,np.NaN)
diabetes.isnull().sum()

/kaggle/input/pima-indians-diabetes-database/diabetes.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB
None
768

Pregnancies                   0
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

In [4]:
# Clearly a lot of values in the data are missing, in fact there are 374 missing values in the Insulin column
# let's print out the rows with the missing values 
print(diabetes[diabetes.isnull().any(axis=1)])
print(diabetes.info())

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6    148.0           72.0           35.0      NaN  33.6
1              1     85.0           66.0           29.0      NaN  26.6
2              8    183.0           64.0            NaN      NaN  23.3
5              5    116.0           74.0            NaN      NaN  25.6
7             10    115.0            NaN            NaN      NaN  35.3
..           ...      ...            ...            ...      ...   ...
761            9    170.0           74.0           31.0      NaN  44.0
762            9     89.0           62.0            NaN      NaN  22.5
764            2    122.0           70.0           27.0      NaN  36.8
766            1    126.0           60.0            NaN      NaN  30.1
767            1     93.0           70.0           31.0      NaN  30.4

     DiabetesPedigreeFunction  Age  Outcome
0                       0.627   50        1
1                       0.351   31        0
2                       0.672   32        1
5                       0.201   30        0
7                       0.134   29        0
..                        ...  ...      ...
761                     0.403   43        1
762                     0.142   33        0
764                     0.340   27        0
766                     0.349   47        1
767                     0.315   23        0

[376 rows x 9 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   763 non-null    float64
 2   BloodPressure             733 non-null    float64
 3   SkinThickness             541 non-null    float64
 4   Insulin                   394 non-null    float64
 5   BMI                       757 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(6), int64(3)
memory usage: 54.1 KB
None

In [7]:
print(diabetes.Outcome.nunique())

2

In [14]:
#Let's look at the value counts in each column
print(diabetes.Pregnancies.value_counts())
print(diabetes.Glucose.value_counts())
print(diabetes.Age.value_counts())
print(diabetes.Age.mean())

1     135
0     111
2     103
3      75
4      68
5      57
6      50
7      45
8      38
9      28
10     24
11     11
13     10
12      9
14      2
15      1
17      1
Name: Pregnancies, dtype: int64
100.0    17
99.0     17
111.0    14
106.0    14
129.0    14
         ..
182.0     1
65.0      1
178.0     1
67.0      1
56.0      1
Name: Glucose, Length: 135, dtype: int64
22    72
21    63
25    48
24    46
23    38
28    35
26    33
27    32
29    29
31    24
41    22
30    21
37    19
42    18
33    17
38    16
36    16
32    16
45    15
34    14
40    13
43    13
46    13
39    12
35    10
52     8
44     8
50     8
51     8
58     7
54     6
47     6
53     5
60     5
49     5
57     5
48     5
66     4
62     4
63     4
55     4
59     3
56     3
65     3
67     3
61     2
69     2
64     1
68     1
70     1
72     1
81     1
Name: Age, dtype: int64
33.240885416666664